2021-07-30 00:23:19.6071 ERROR Error while running updates check:. Exception: Nord.Updater.Flare.Net.FlareException: Failed to check for update. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'downloads.nordcdn.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.Feed.FeedDownloader.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateDownloader.<GetUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateManager.<FindNewestUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nord.Updater.UpdateManager.<RunUpdater>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.UpdateManager.<RunAsync>d__40.MoveNext()
2021-07-30 00:23:19.8800 INFO Initializing UpdateManager; iDelay: 3600, cDelay: 3600.
2021-07-30 00:23:19.9737 INFO Running update check. Current app version: NordVPN/6.37.5.0
2021-07-30 05:46:36.4307 ERROR Error while running updates check:. Exception: Nord.Updater.Flare.Net.FlareException: Failed to check for update. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'downloads.nordcdn.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.Feed.FeedDownloader.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateDownloader.<GetUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateManager.<FindNewestUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nord.Updater.UpdateManager.<RunUpdater>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.UpdateManager.<RunAsync>d__40.MoveNext()
2021-07-30 05:46:36.7815 INFO Initializing UpdateManager; iDelay: 3600, cDelay: 3600.
2021-07-30 05:46:36.8345 INFO Running update check. Current app version: NordVPN/6.37.5.0
2021-07-30 06:47:21.5072 ERROR Error while running updates check:. Exception: Nord.Updater.Flare.Net.FlareException: Failed to check for update. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'downloads.nordcdn.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.Feed.FeedDownloader.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateDownloader.<GetUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateManager.<FindNewestUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nord.Updater.UpdateManager.<RunUpdater>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.UpdateManager.<RunAsync>d__40.MoveNext()
2021-07-30 06:47:21.6322 INFO Initializing UpdateManager; iDelay: 3600, cDelay: 3600.
2021-07-30 06:47:21.6478 INFO Running update check. Current app version: NordVPN/6.37.5.0
2021-07-30 07:48:05.0150 INFO New update found: 6.38.15; current version: 6.37.5.0
2021-07-30 07:48:05.0150 INFO Starting to download update
2021-07-30 07:48:24.7732 INFO Update file download finished
2021-07-30 13:35:26.7849 ERROR Error while running updates check:. Exception: Nord.Updater.Flare.Net.FlareException: Failed to check for update. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'downloads.nordcdn.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.Feed.FeedDownloader.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateDownloader.<GetUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.Internals.UpdateManager.<FindNewestUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Nord.Updater.Flare.Net.FlareUpdater.<CheckForUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nord.Updater.UpdateManager.<RunUpdater>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nord.Updater.UpdateManager.<RunAsync>d__40.MoveNext()
2021-07-30 13:35:27.0349 INFO Initializing UpdateManager; iDelay: 3600, cDelay: 3600.
2021-07-30 13:35:27.0818 INFO Running update check. Current app version: NordVPN/6.37.5.0
